# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian's Website
email: bweyl@udel.edu
description: Personal Website of Brian Weyl - Powered by Jekyll with Gravity theme
baseurl: # the subpath of your site, e.g. /blog
url: "b-weyl.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  B-Weyl
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
